export const factoryABI = [
  {
    name: "NewExchange",
    inputs: [
      { type: "address", name: "token", indexed: true },
      { type: "address", name: "exchange", indexed: true },
    ],
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_creationFee",
        type: "uint256",
      },
    ],
    name: "changeCreationFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "creationFee",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    name: "initializeFactory",
    outputs: [],
    inputs: [{ type: "address", name: "template" }],
    constant: false,
    payable: false,
    type: "function",
    gas: 35725,
  },
  {
    name: "createExchange",
    outputs: [{ type: "address", name: "out" }],
    inputs: [{ type: "address", name: "token" }],
    constant: false,
    payable: false,
    type: "function",
    gas: 187911,
  },
  {
    name: "getExchange",
    outputs: [{ type: "address", name: "out" }],
    inputs: [{ type: "address", name: "token" }],
    constant: true,
    payable: false,
    type: "function",
    gas: 715,
  },
  {
    name: "getToken",
    outputs: [{ type: "address", name: "out" }],
    inputs: [{ type: "address", name: "exchange" }],
    constant: true,
    payable: false,
    type: "function",
    gas: 745,
  },
  {
    name: "getTokenWithId",
    outputs: [{ type: "address", name: "out" }],
    inputs: [{ type: "uint256", name: "token_id" }],
    constant: true,
    payable: false,
    type: "function",
    gas: 736,
  },
  {
    name: "exchangeTemplate",
    outputs: [{ type: "address", name: "out" }],
    inputs: [],
    constant: true,
    payable: false,
    type: "function",
    gas: 633,
  },
  {
    name: "tokenCount",
    outputs: [{ type: "uint256", name: "out" }],
    inputs: [],
    constant: true,
    payable: false,
    type: "function",
    gas: 663,
  },
]
